### ISSUE TITLE
Formula typo in 《Proof-Carrying Data from Accumulation Schemes》?

### ISSUE THREAD

**Issue by 3for** [scipr-lab/poly-commit#39]
I‘m reading the paper [Proof-Carrying Data from Accumulation Schemes](https://eprint.iacr.org/2020/499.pdf)，and there maybe something wrong in the "Figuer 1" `Open` setup evaluation formula, just as shown below：

![image](https://user-images.githubusercontent.com/30716372/92193485-089bef00-ee9b-11ea-9b7d-cebdd73104de.png)

And "Figuer 1" has no reference in the paper anywhere.

**Comment by 3for** [comment]
And the evaluation equation in `check` step should be the one below?
![image](https://user-images.githubusercontent.com/30716372/92204688-9cc77f80-eeb6-11ea-9f12-3de71fc6e9b1.png)

**Comment by Pratyush** [comment]
Hi @3for 

Thanks for pointing these errors out! I have fixed these errors in our local version of the paper, and will push an update to the ePrint version shortly. How would you like to be acknowledged in the paper? I was thinking of going with:

"Thanks to Github user 3for for pointing out errors in the description of PC_AGM in figure 1."

If you have a real name that you would prefer I use instead, then I can do that. Thanks!

**Comment by 3for** [comment]
"Yudi Zou" or "3for", both are okay.  It's my pleasure to be helpful.
